apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: react-ro
  namespace: reactapp
spec:
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: avaeusk8sacrpoc.azurecr.io/react-svc:36
      imagePullSecrets:
        - name: k8simagesecret
  selector:
    matchLabels:
      app: reactapp
  replicas: 3
  strategy:
    canary:
      steps:
      - setCanaryScale: 
          weight: 20
      # 90% of traffic to the 1 canary pod
      - setWeight: 90
      - pause: {}
