apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: react-ro
  namespace: reactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: avaeusk8sacrpoc.azurecr.io/react-svc:32
      imagePullSecrets:
        - name: k8simagesecret
  strategy:
    canary:
      steps:
        - setWeight: 10
          trafficRouting:
            type: SetCanaryScale
            weight: 20
        - pause: {}
        - setWeight: 90
