apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: react-ro
  namespace: reactapp
spec:
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: avaeusk8sacrpoc.azurecr.io/react-svc:32
      imagePullSecrets:
        - name: k8simagesecret
  selector:
    matchLabels:
      app: reactapp
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 40
      - pause: {}
